# Generated by Django 2.1.5 on 2019-04-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=10)),
                ('job_title', models.CharField(max_length=100)),
                ('responsibilities', models.TextField()),
                ('skills', models.TextField()),
                ('experiences', models.TextField()),
                ('requirements', models.TextField()),
                ('contact', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('job_id', models.CharField(max_length=10)),
                ('job_title', models.CharField(max_length=100)),
                ('working_time', models.CharField(max_length=30)),
                ('why_bm', models.TextField()),
                ('skills_experience', models.TextField()),
                ('resume', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
