# Generated by Django 2.1.5 on 2019-04-03 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', max_length=20, verbose_name='Popular Keywords')),
                ('index', models.IntegerField(default=0, verbose_name='Index')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'Popular Searches',
                'verbose_name_plural': 'Popular Searches',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('TRANSACTION_SUCCESS', 'Success'), ('TRANSACTION_CLOSED', 'Close'), ('TRANSACTION_FINISHED', 'Finish'), ('TRANSACTION_CANCELED', 'Cancel'), ('TRANSACTION_FAILED', 'Fail'), ('TRANSACTION_SUBMITTED', 'Submit')], default='TRANSACTION_SUBMITTED', max_length=30, verbose_name='Order Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.CharField(choices=[('credit', 'CreditCard'), ('stripe', 'Stripe'), ('paypal', 'Paypal'), ('check', 'Check')], default='stripe', max_length=12, verbose_name='Pay Type'),
        ),
    ]
