# Generated by Django 2.1.5 on 2019-04-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(max_length=100)),
                ('image', models.TextField()),
                ('msrp', models.CharField(max_length=100)),
                ('monthly_payment', models.CharField(max_length=100)),
                ('drive_off', models.CharField(default='0', max_length=100)),
                ('other_info', models.CharField(max_length=100)),
                ('promotion_year', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current', models.CharField(default='0', max_length=5)),
                ('entered_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(max_length=100)),
                ('image', models.TextField()),
                ('msrp', models.CharField(max_length=100)),
                ('monthly_payment', models.CharField(max_length=100)),
                ('drive_off', models.CharField(default='0', max_length=100)),
                ('other_info', models.CharField(max_length=100)),
                ('promotion_year', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current', models.CharField(default='0', max_length=5)),
                ('entered_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
