# Generated by Django 2.1.5 on 2019-04-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklydeal',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weeklydeal',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
