# Generated by Django 2.1.5 on 2019-02-07 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('cartype', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=30)),
                ('competitors', models.TextField()),
                ('mpg', models.CharField(max_length=50)),
                ('msrp', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('source_url', models.TextField()),
                ('shopping_url', models.TextField()),
            ],
            options={
                'db_table': 'car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('cartype', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=30)),
                ('source_url', models.TextField()),
                ('path_key', models.TextField()),
                ('path_value', models.TextField()),
            ],
            options={
                'db_table': 'car_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarImagePath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path_key', models.TextField()),
                ('path_dest', models.TextField()),
            ],
            options={
                'db_table': 'car_image_path',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('source_url', models.TextField(blank=True, default='')),
                ('description', models.CharField(max_length=255)),
                ('logo', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'car_make',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('referer', models.TextField(blank=True, default='')),
                ('logo', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'car_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarSpecs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('cartype', models.CharField(max_length=100)),
                ('trim', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=30)),
                ('style', models.TextField()),
                ('seats', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('mpg', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=255)),
                ('drivetrain', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=255)),
                ('source_url', models.TextField()),
            ],
            options={
                'db_table': 'car_specs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarTrim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('cartype', models.CharField(max_length=100)),
                ('trim', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=30)),
                ('style', models.TextField()),
                ('mpg', models.CharField(max_length=50)),
                ('msrp', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
                ('engine', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=255)),
                ('drivetrain', models.CharField(max_length=100)),
                ('source_url', models.TextField()),
                ('specs_url', models.TextField()),
            ],
            options={
                'db_table': 'car_trim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('logo', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'car_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('office_phone', models.CharField(max_length=20)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=30)),
                ('msrp', models.CharField(max_length=100)),
                ('sale_price', models.CharField(max_length=100)),
                ('rebate', models.CharField(max_length=100)),
                ('res', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=100)),
                ('yearly_mileage', models.CharField(max_length=100)),
                ('money_factor', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Dealer')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('office_phone', models.CharField(max_length=20)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('address_3', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Dealer')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=16)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Profile'),
        ),
    ]
