# Generated by Django 2.1.5 on 2019-05-07 20:27

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('session_id', models.UUIDField()),
                ('direction', models.CharField(max_length=20)),
                ('message', django.contrib.postgres.fields.jsonb.JSONField()),
                ('dialogflow_resp', django.contrib.postgres.fields.jsonb.JSONField()),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
        ),
    ]
