# Generated by Django 2.1.5 on 2019-04-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('cartype', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=30)),
                ('competitors', models.TextField()),
                ('mpg', models.CharField(max_length=50)),
                ('msrp', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('source_url', models.TextField()),
                ('shopping_url', models.TextField()),
            ],
            options={
                'db_table': 'car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('cartype', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=30)),
                ('source_url', models.TextField()),
                ('path_key', models.TextField()),
                ('path_value', models.TextField()),
            ],
            options={
                'db_table': 'car_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarImagePath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path_key', models.TextField()),
                ('path_dest', models.TextField()),
            ],
            options={
                'db_table': 'car_image_path',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('source_url', models.TextField(blank=True, default='')),
                ('description', models.CharField(max_length=255)),
                ('logo', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'car_make',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('referer', models.TextField(blank=True, default='')),
                ('logo', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'car_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarSpecs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('cartype', models.CharField(max_length=100)),
                ('trim', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=30)),
                ('style', models.TextField()),
                ('seats', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('mpg', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=255)),
                ('drivetrain', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=255)),
                ('source_url', models.TextField()),
            ],
            options={
                'db_table': 'car_specs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarTrim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('cartype', models.CharField(max_length=100)),
                ('trim', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=30)),
                ('style', models.TextField()),
                ('mpg', models.CharField(max_length=50)),
                ('msrp', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
                ('engine', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=255)),
                ('drivetrain', models.CharField(max_length=100)),
                ('source_url', models.TextField()),
                ('specs_url', models.TextField()),
            ],
            options={
                'db_table': 'car_trim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('logo', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'car_type',
                'managed': False,
            },
        ),
    ]
