# Generated by Django 2.1.5 on 2019-04-02 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carimagepath',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carmake',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carspecs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cartrim',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cartype',
            options={},
        ),
    ]
