# Generated by Django 2.1.5 on 2019-04-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20190402_0206'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table=None,
        ),
        migrations.AlterModelTable(
            name='carimage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='carimagepath',
            table=None,
        ),
        migrations.AlterModelTable(
            name='carmake',
            table=None,
        ),
        migrations.AlterModelTable(
            name='carmodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='carspecs',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cartrim',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cartype',
            table=None,
        ),
    ]
