# Generated by Django 2.1.5 on 2019-04-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20190402_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='carimage',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='carimagepath',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='carmake',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='carspecs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cartrim',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cartype',
            options={'managed': False},
        ),
    ]
