# Generated by Django 2.1.5 on 2019-04-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20190403_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimage',
            options={'managed': False},
        ),
    ]
