# Generated by Django 2.1.5 on 2019-04-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20190405_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='carimage',
            table='cars_carimage',
        ),
    ]
