# Generated by Django 2.1.5 on 2019-04-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20190407_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(max_length=100)),
                ('msrp', models.FloatField(default=0.0)),
                ('sale_price', models.FloatField(default=0.0)),
                ('rebate', models.FloatField(default=55.0)),
                ('res', models.FloatField(default=55.0)),
                ('term', models.FloatField(default=36.0)),
                ('yearly_mileage', models.FloatField(default=10000.0)),
                ('money_factor', models.FloatField(default=0.0002)),
                ('deposit', models.CharField(max_length=50)),
                ('due', models.CharField(max_length=50)),
                ('payment', models.FloatField(default=0.0)),
                ('invoice', models.FloatField()),
                ('residual', models.FloatField()),
                ('comment', models.TextField()),
                ('dealer_id', models.TextField(default='Bliss Motors')),
                ('car_id', models.TextField(default='Car ID')),
            ],
        ),
        migrations.AlterModelTable(
            name='car',
            table='cars_car',
        ),
    ]
