# Generated by Django 2.1.5 on 2019-04-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20190408_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyFactor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(max_length=100)),
                ('mo_24', models.FloatField(default=0.0)),
                ('mo_27', models.FloatField(default=0.0)),
                ('mo_30', models.FloatField(default=0.0)),
                ('mo_33', models.FloatField(default=0.0)),
                ('mo_36', models.FloatField(default=0.0)),
                ('mo_39', models.FloatField(default=0.0)),
                ('mo_42', models.FloatField(default=0.0)),
                ('mo_45', models.FloatField(default=0.0)),
                ('mo_48', models.FloatField(default=0.0)),
                ('mo_51', models.FloatField(default=0.0)),
                ('mo_54', models.FloatField(default=0.0)),
                ('mo_57', models.FloatField(default=0.0)),
                ('mo_60', models.FloatField(default=0.0)),
                ('tier_4', models.FloatField(default=0.0)),
                ('tier_5', models.FloatField(default=0.0)),
                ('tier_6', models.FloatField(default=0.0)),
                ('tier_7', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ResidualValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(max_length=100)),
                ('mo_24', models.FloatField(default=0.0)),
                ('mo_27', models.FloatField(default=0.0)),
                ('mo_30', models.FloatField(default=0.0)),
                ('mo_33', models.FloatField(default=0.0)),
                ('mo_36', models.FloatField(default=0.0)),
                ('mo_39', models.FloatField(default=0.0)),
                ('mo_42', models.FloatField(default=0.0)),
                ('mo_45', models.FloatField(default=0.0)),
                ('mo_48', models.FloatField(default=0.0)),
                ('mo_51', models.FloatField(default=0.0)),
                ('mo_54', models.FloatField(default=0.0)),
                ('mo_57', models.FloatField(default=0.0)),
                ('mo_60', models.FloatField(default=0.0)),
                ('mi_10k', models.FloatField(default=0.0)),
                ('mi_12k', models.FloatField(default=0.0)),
                ('mi_15k', models.FloatField(default=0.0)),
                ('multiple_factor', models.IntegerField(default=1)),
                ('multiple_mo', models.IntegerField(default=24)),
            ],
        ),
    ]
